services:
  spring-project:
    image: 'endterm-spring-project'
    container_name: 'spring-project'
    depends_on:
      - database-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database-service:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_FLYWAY_ENABLED=false
    ports:
      - 8888:8080

  database-service:
    image: 'postgres:14'
    container_name: 'database-service'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 2345:5432

  database-service-test:
    image: 'postgres:14'
    container_name: 'database-service-test'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - 2346:5432

